export const INIT_SAVE_USERS_VALUE = "INIT_SAVE_USERS_VALUE";
export const SAVE_USERS_VALUE_SUCCESSFULL = "SAVE_USERS_VALUE_SUCCESSFULL";
export const SAVE_USERS_VALUE_FAILED = "SAVE_USERS_VALUE_FAILED";