export const INIT_SAVE_TRUCKS_VALUE = "INIT_SAVE_TRUCKS_VALUE";
export const SAVE_TRUCKS_VALUE_SUCCESSFULL = "SAVE_TRUCKS_VALUE_SUCCESSFULL";
export const SAVE_TRUCKS_VALUE_FAILED = "SAVE_TRUCKS_VALUE_FAILED";