export const INIT_GET_LIST_USER = "INIT_GET_LIST_USER";
export const FETCHING_GET_LIST_USER = "FETCHING_GET_LIST_USER";
export const FETCHING_GET_LIST_USER_SUCCESS = "FETCHING_GET_LIST_USER_SUCCESS";
export const FETCHING_GET_LIST_USER_FAILED = "FETCHING_GET_LIST_USER_FAILED";