export const INIT_SAVE_CARGO_VALUE = "INIT_SAVE_CARGO_VALUE";
export const SAVE_CARGO_VALUE_SUCCESSFULL = "SAVE_CARGO_VALUE_SUCCESSFULL";
export const SAVE_CARGO_VALUE_FAILED = "SAVE_CARGO_VALUE_FAILED";