export const INIT_GET_LIST_DRIVER = "INIT_GET_LIST_DRIVER";
export const FETCHING_GET_LIST_DRIVER = "FETCHING_GET_LIST_DRIVER";
export const FETCHING_GET_LIST_DRIVER_SUCCESS = "FETCHING_GET_LIST_DRIVER_SUCCESS";
export const FETCHING_GET_LIST_DRIVER_FAILED = "FETCHING_GET_LIST_DRIVER_FAILED";