export const INIT_GET_LIST_TRUCK = "INIT_GET_LIST_TRUCK";
export const FETCHING_GET_LIST_TRUCK = "FETCHING_GET_LIST_TRUCK";
export const FETCHING_GET_LIST_TRUCK_SUCCESS = "FETCHING_GET_LIST_TRUCK_SUCCESS";
export const FETCHING_GET_LIST_TRUCK_FAILED = "FETCHING_GET_LIST_TRUCK_FAILED";