export const INIT_GET_LIST_CARGO = "INIT_GET_LIST_CARGO";
export const FETCHING_GET_LIST_CARGO = "FETCHING_GET_LIST_CARGO";
export const FETCHING_GET_LIST_CARGO_SUCCESS = "FETCHING_GET_LIST_CARGO_SUCCESS";
export const FETCHING_GET_LIST_CARGO_FAILED = "FETCHING_GET_LIST_CARGO_FAILED";